"""
@module MOD-IB-01
@implements IFC-IB-001..012（汇总导出）
@depends (none)
@author software-developer

核心契约层唯一导出面。上层模块一律 `from ib.core import Scope, VectorStore, ...`，
**不**直接 import 子模块，使未来的契约内部重构不影响调用方。

**framework-free 不变式**：本包（含子模块）只允许 stdlib。
`src/scripts/selfcheck.py::check_core_framework_free` 在干净子进程中断言这一点。
"""

from __future__ import annotations

from . import enums, errors, ports, types
from .enums import (
    DegradeReason,
    DocStatus,
    RebuildState,
    RouteTier,
    SourceKind,
    StreamEventKind,
)
from .errors import (
    ConflictError,
    ConfigError,
    DependencyUnavailableError,
    IbError,
    NotFoundError,
    ScopeViolationError,
    StartupError,
    ValidationError,
)
from .ports import (
    AuthzPolicy,
    BlobStore,
    Chunker,
    CollectionResolver,
    ConfigurationSource,
    DocumentParser,
    Embedder,
    LedgerRepository,
    LlmProvider,
    OcrEngine,
    PageRenderer,
    SessionStore,
    VectorStore,
)
from .types import (
    AuthzContext,
    BlobRef,
    BoundTool,
    ChunkImageRecord,
    ChunkRecord,
    ChunkingSpec,
    CollectionInfo,
    CollectionSpec,
    DeleteReport,
    DocumentRecord,
    EmbedderDescriptor,
    EgressDescriptor,
    ExpertResult,
    ExpertSpec,
    GraphConfig,
    HealthStatus,
    HnswParams,
    KbRecord,
    LlmRole,
    Message,
    OcrDescriptor,
    PageImageBinding,
    PageImageRef,
    PageImageSourceKindLiteral,
    ParsedChunk,
    ParsedDocument,
    PointFilter,
    PointPayload,
    ProcessReport,
    ProjectRecord,
    RawConfig,
    RebuildJob,
    RebuildPlan,
    RebuildProgress,
    RegisteredTool,
    RelatedImageItem,
    RelatedImagesPayload,
    RequestContext,
    RetrievalResult,
    RetrievedChunk,
    RouteDecision,
    ScoredPoint,
    Scope,
    SessionState,
    StreamEvent,
    ToolResult,
    ToolSpec,
    UpsertResult,
    ValidatedUpload,
    Vector,
    VectorPoint,
)

__all__ = [
    # 子模块（便于 `from ib.core import ports` 这类内省用法）
    "enums",
    "errors",
    "types",
    "ports",
    # 枚举
    "DocStatus",
    "SourceKind",
    "DegradeReason",
    "RouteTier",
    "StreamEventKind",
    "RebuildState",
    # 异常
    "IbError",
    "ConfigError",
    "ScopeViolationError",
    "DependencyUnavailableError",
    "ValidationError",
    "NotFoundError",
    "ConflictError",
    "StartupError",
    # 数据结构
    "Vector",
    "Scope",
    "HnswParams",
    "CollectionSpec",
    "CollectionInfo",
    "PointPayload",
    "VectorPoint",
    "ScoredPoint",
    "PointFilter",
    "UpsertResult",
    "HealthStatus",
    "EmbedderDescriptor",
    "ChunkingSpec",
    "ParsedChunk",
    "ParsedDocument",
    "RetrievedChunk",
    "RetrievalResult",
    "PageImageRef",
    "PageImageBinding",
    "PageImageSourceKindLiteral",
    "RelatedImageItem",
    "RelatedImagesPayload",
    "ChunkImageRecord",
    "DocumentRecord",
    "ChunkRecord",
    "KbRecord",
    "ProjectRecord",
    "AuthzContext",
    "RequestContext",
    "RawConfig",
    "BlobRef",
    "ValidatedUpload",
    "ProcessReport",
    "DeleteReport",
    "RebuildPlan",
    "RebuildJob",
    "RebuildProgress",
    "ToolResult",
    "ToolSpec",
    "BoundTool",
    "RegisteredTool",
    "ExpertSpec",
    "Message",
    "RouteDecision",
    "LlmRole",
    "EgressDescriptor",
    "OcrDescriptor",
    "SessionState",
    "StreamEvent",
    "ExpertResult",
    "GraphConfig",
    # 端口
    "ConfigurationSource",
    "AuthzPolicy",
    "DocumentParser",
    "OcrEngine",
    "Chunker",
    "PageRenderer",
    "Embedder",
    "CollectionResolver",
    "VectorStore",
    "LedgerRepository",
    "BlobStore",
    "LlmProvider",
    "SessionStore",
]
