"""
@module MOD-IB-01
@implements IFC-IB-001..012（汇总导出）
            IFC-IB-337 ~ 342 / 339（REV-16-2 提示词 / 工具参数 / 第 16 个端口汇总导出）
            IFC-IB-355 ~ 363（REV-16-4 统合校验 / 存储态 / 配置审计 / 第 17 个端口汇总导出）
@depends (none)
@author software-developer

核心契约层唯一导出面。上层模块一律 `from ib.core import Scope, VectorStore, ...`，
**不**直接 import 子模块，使未来的契约内部重构不影响调用方。

**framework-free 不变式**：本包（含子模块）只允许 stdlib。
`src/scripts/selfcheck.py::check_core_framework_free` 在干净子进程中断言这一点。
"""

from __future__ import annotations

from . import accounts, enums, errors, ports, types
from .accounts import (
    new_session_token,
    token_digest,
    token_digest_matches,
)
from .enums import (
    DegradeReason,
    DocStatus,
    RebuildState,
    RouteTier,
    SourceKind,
    StreamEventKind,
)
from .errors import (
    ConflictError,
    ConfigError,
    DependencyUnavailableError,
    IbError,
    NotFoundError,
    PromptNotFoundError,
    ScopeViolationError,
    StartupError,
    ToolParamValidationError,
    ValidationError,
)
from .ports import (
    AccountStore,
    AuthzPolicy,
    BlobStore,
    Chunker,
    CollectionResolver,
    ConfigAuditStore,
    ConfigurationSource,
    DefinitionDocumentStore,
    DocumentParser,
    Embedder,
    ExpertPromptStore,
    LedgerRepository,
    LlmProvider,
    OcrEngine,
    PageRenderer,
    SessionStore,
    VectorStore,
)
from .types import (
    DEFAULT_SESSION_PERSISTENCE_POLICY,
    RESERVED_GRAPH_ENDPOINTS,
    SESSION_STATE_LOSS_OUTCOME,
    AccountStatus,
    AccountSummary,
    AuthzContext,
    BlobRef,
    BoundTool,
    ChunkImageRecord,
    ChunkRecord,
    ChunkingSpec,
    CitationItem,
    CollectionInfo,
    CollectionSpec,
    CompletionPayload,
    ConditionalEdgeSpec,
    ConfigAuditEntry,
    ConfigAuditResult,
    ConfirmationDecision,
    ConfirmationGateState,
    ConfirmationPrompt,
    DefinitionDocument,
    DeleteReport,
    DerivedView,
    DimensionCheck,
    DocumentRecord,
    EdgeSpec,
    EmbedderDescriptor,
    EgressDescriptor,
    ExpertPromptBundle,
    ExpertPromptDocumentRef,
    ExpertResult,
    ExpertSpec,
    ExpertSpecInput,
    AlignmentChecklist,
    FreeArkAlignedExpertSpec,
    GraphConfig,
    HealthStatus,
    HnswParams,
    KbRecord,
    LlmRole,
    LoginOutcome,
    Message,
    OcrDescriptor,
    OrchestrationSpecInput,
    PageImageBinding,
    PageImageRef,
    PageImageSourceKindLiteral,
    ParsedChunk,
    ParsedDocument,
    PasswordPolicy,
    PointFilter,
    PointPayload,
    ProcessReport,
    ProjectRecord,
    PromptDirectoryLayout,
    PromptLayer,
    PromptSaveResult,
    RawConfig,
    RebuildJob,
    RebuildPlan,
    RebuildProgress,
    RegisteredTool,
    RelatedImageItem,
    RelatedImagesPayload,
    RequestContext,
    RetrievalResult,
    RetrievedChunk,
    RouteDecision,
    RouteSpecInput,
    SaveResult,
    ScoredPoint,
    Scope,
    SessionPersistencePolicy,
    SessionRecord,
    SessionState,
    SessionStateLossOutcome,
    SessionTurn,
    StorageState,
    StoreMode,
    StreamEvent,
    ToolGrantSpec,
    ToolParamSpec,
    ToolParamTypeLiteral,
    ToolParamValue,
    ToolResult,
    ToolSpec,
    UpsertResult,
    UserRecord,
    UserRole,
    ValidatedUpload,
    ValidationErrorItem,
    ValidationReport,
    Vector,
    VectorPoint,
)

__all__ = [
    # 子模块（便于 `from ib.core import ports` 这类内省用法）
    "enums",
    "errors",
    "types",
    "ports",
    "accounts",
    # 枚举
    "DocStatus",
    "SourceKind",
    "DegradeReason",
    "RouteTier",
    "StreamEventKind",
    "RebuildState",
    # 异常
    "IbError",
    "ConfigError",
    "ScopeViolationError",
    "DependencyUnavailableError",
    "ValidationError",
    "NotFoundError",
    "ConflictError",
    "StartupError",
    "PromptNotFoundError",
    "ToolParamValidationError",
    # 数据结构
    "Vector",
    "Scope",
    "HnswParams",
    "CollectionSpec",
    "CollectionInfo",
    "PointPayload",
    "VectorPoint",
    "ScoredPoint",
    "PointFilter",
    "UpsertResult",
    "HealthStatus",
    "EmbedderDescriptor",
    "ChunkingSpec",
    "ParsedChunk",
    "ParsedDocument",
    "RetrievedChunk",
    "RetrievalResult",
    "PageImageRef",
    "PageImageBinding",
    "PageImageSourceKindLiteral",
    "RelatedImageItem",
    "RelatedImagesPayload",
    "ChunkImageRecord",
    "DocumentRecord",
    "ChunkRecord",
    "KbRecord",
    "ProjectRecord",
    "AuthzContext",
    "RequestContext",
    # R13 账户 / 会话（IFC-IB-309）
    "UserRole",
    "AccountStatus",
    "LoginOutcome",
    "UserRecord",
    "SessionRecord",
    "PasswordPolicy",
    "AccountSummary",
    "RawConfig",
    "BlobRef",
    "ValidatedUpload",
    "ProcessReport",
    "DeleteReport",
    "RebuildPlan",
    "RebuildJob",
    "RebuildProgress",
    "ToolResult",
    "ToolSpec",
    "BoundTool",
    "RegisteredTool",
    "ExpertSpec",
    "Message",
    "RouteDecision",
    "LlmRole",
    "EgressDescriptor",
    "OcrDescriptor",
    "SessionState",
    "SessionTurn",
    "StreamEvent",
    "ExpertResult",
    "GraphConfig",
    # R8 会话 / 确认中间态 / 完成产物（IFC-IB-298~301）
    "CitationItem",
    "CompletionPayload",
    "ConfirmationPrompt",
    "ConfirmationDecision",
    "ConfirmationGateState",
    "SessionPersistencePolicy",
    "SessionStateLossOutcome",
    "DEFAULT_SESSION_PERSISTENCE_POLICY",
    "SESSION_STATE_LOSS_OUTCOME",
    # R7 定义文档数据结构（IFC-IB-287~292）
    "ExpertSpecInput",
    "RouteSpecInput",
    "ConditionalEdgeSpec",
    "EdgeSpec",
    "RESERVED_GRAPH_ENDPOINTS",
    "OrchestrationSpecInput",
    "ToolGrantSpec",
    "DefinitionDocument",
    "DerivedView",
    "ValidationErrorItem",
    "ValidationReport",
    "SaveResult",
    # REV-16-2 提示词 / 工具参数（IFC-IB-337 ~ 342）
    "PromptLayer",
    "ToolParamTypeLiteral",
    "ExpertPromptDocumentRef",
    "ExpertPromptBundle",
    "PromptDirectoryLayout",
    "ToolParamValue",
    "ToolParamSpec",
    "PromptSaveResult",
    "DimensionCheck",
    "AlignmentChecklist",
    "FreeArkAlignedExpertSpec",
    # 端口
    "ConfigurationSource",
    "AuthzPolicy",
    "DocumentParser",
    "OcrEngine",
    "Chunker",
    "PageRenderer",
    "Embedder",
    "CollectionResolver",
    "VectorStore",
    "LedgerRepository",
    "BlobStore",
    "LlmProvider",
    "SessionStore",
    "DefinitionDocumentStore",
    # R13 第 15 个端口 + 令牌原语（IFC-IB-310 / 311）
    "AccountStore",
    "new_session_token",
    "token_digest",
    "token_digest_matches",
    # REV-16-2 第 16 个端口（IFC-IB-339）
    "ExpertPromptStore",
    # REV-16-4 存储态 / 配置审计（IFC-IB-356 ~ 362）
    "ConfigAuditResult",
    "StoreMode",
    "ConfigAuditEntry",
    "StorageState",
    # REV-16-4 第 17 个端口（IFC-IB-357）
    "ConfigAuditStore",
]
